version: '3.8'

services:
  app:
    build: .
    expose:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=popcorntime
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=popcorntime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d popcorntime"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Если нужен HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Конфиг Nginx
      - ./static:/var/www/html  # Статические файлы (опционально)
    depends_on:
      - app
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge